version: "3.8"

services:
  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
      
  keycloak:
    image: "jboss/keycloak:15.0.2"
    environment:
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_ADDR: "keycloak-database"
      DB_USER: "keycloak"
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_DATABASE: "keycloak"
      KEYCLOAK_FRONTEND_URL: "http://localhost:8088/auth"
    ports:
      - "8088:8080"
  keycloak-database:
    image: "postgres:13.2-alpine"
    environment:
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - "keycloak_data:/var/lib/postgresql/data"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    
  datastore-application:
    image: hu.microservice.medicare/datastore-application:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database/${DB_NAME}"
      SPRING_DATASOURCE_TYPE: "org.apache.tomcat.jdbc.pool.DataSource"
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_TOMCAT_MIN_IDLE: ${CONNECTION_POOL_MIN_SIZE}
      SPRING_DATASOURCE_TOMCAT_MAX_IDLE: ${CONNECTION_POOL_MAX_SIZE}
      SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE: ${CONNECTION_POOL_MIN_SIZE}
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_DATABASEPLATFORM: "org.hibernate.dialect.PostgreSQL95Dialect"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: ${OAUTH2_JWT_ISSUER_URI}
      MEDICARE_WEB_SECURITY_ENABLED: "true"
      MEDICARE_WEB_SECURITY_JWKS_URI: ${OAUTH2_JWKS_URI}
      MEDICARE_PROJECT_USER_URL: "http://user-service:8080"
    ports:
      - "8085:8080"

  neural-processor-application:
    image: hu.microservice.medicare/neural-processor-application:0.0.1-SNAPSHOT
    environment:
      MEDICARE_WEB_SECURITY_ENABLED: "true"
      MEDICARE_WEB_SECURITY_JWKS_URI: ${OAUTH2_JWKS_URI}
    ports:
      - "8091:8080"
      
  calculator-application:
    image: hu.microservice.medicare/calculator-application:0.0.1-SNAPSHOT
    environment:
      MEDICARE_PROJECT_DATASTORE_URL: "http://datastore-application:8080"
      MEDICARE_PROJECT_NEURAL_URL: "http://neural-processor-application:8080"
      MEDICARE_WEB_SECURITY_ENABLED: "true"
      MEDICARE_WEB_SECURITY_JWKS_URI: ${OAUTH2_JWKS_URI}
    ports:
      - "8095:8080"
      
  user-service:
    image: hu.microservice.medicare/medicare-user-application:0.0.1-SNAPSHOT
    environment:
      MEDICARE_WEB_SECURITY_ENABLED: "true"
      MEDICARE_WEB_SECURITY_JWKS_URI: ${OAUTH2_JWKS_URI}
      SERVER_FORWARDHEADERSSTRATEGY: "FRAMEWORK"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: ${OAUTH2_JWT_ISSUER_URI}
      KEYCLOAK_URI: "http://keycloak:8080"
    ports:
      -  "8097:8080"
    
volumes:
  keycloak_data:
  database-data: