package hu.microservice.medicare.datastore;

public enum IllnessCategory {
	BLOOD,
	CANCER_AND_NEOPLASMS,
	CARDIOVASCULAR,
	EAR,
	EYE,
	INFECTION,
	INFLAMMATORY_AND_IMMUNE_SYSTEM,
	INJURIES_AND_ACCIDENTS,
	MENTAL_HEALTH,
	METABOLIC_AND_ENDOCRINE,
	MUSCULOSKELETAL,
	NEUROLOGICAL,
	ORAL_AND_GASTROINTESTINAL,
	RENAL_AND_UROGENITAL,
	REPRODUCTIVE_HEALTH_AND_CHILDBIRTH,
	RESPIRATORY,
	SKIN,
	STROKE,
	UNKNOWN;
}
