package hu.microservice.medicare.datastore;

public enum JobType {
	STUDENT,
	STUDENT_AND_WORKING,
	AGRICULTURE,
	ARCHITECTURE_AND_CONSTRUCTION,
	ARTS,
	BUSINESS_AND_FINANCE,
	EDUCATION_AND_TRAINING,
	GOVERNMENT_AND_PUBLIC_ADMINISTRATION,
	HEALTH,
	INFORMATION_TECHNOLOGY,
	FASHION,
	GOODS,
	SERVICE_CONTRACT,
	HOSPITALITY,
	RETIRED;
}
